<?php

namespace ContainerXSsO7kI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UdS6csrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UdS6csr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UdS6csr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nota' => ['privates', '.errored..service_locator.UdS6csr.App\\Entity\\Nota', NULL, 'Cannot autowire service ".service_locator.UdS6csr": it references class "App\\Entity\\Nota" but no such service exists.'],
            'notaRepository' => ['privates', 'App\\Repository\\NotaRepository', 'getNotaRepositoryService', true],
        ], [
            'nota' => 'App\\Entity\\Nota',
            'notaRepository' => 'App\\Repository\\NotaRepository',
        ]);
    }
}
