<?php

namespace ContainerXSsO7kI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dl9tJ6AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dl9tJ6A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dl9tJ6A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\NotaController::busqueda' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController::delete' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\NotaController::edit' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\NotaController::eliminadas' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController::index' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController::publicas' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController::restaurar' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\RegistrationController::busqueda' => ['privates', '.service_locator.cbR_.A0', 'get_ServiceLocator_CbR_A0Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\NotaController:busqueda' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController:delete' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\NotaController:edit' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\NotaController:eliminadas' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController:index' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController:publicas' => ['privates', '.service_locator.plCz5Pj', 'get_ServiceLocator_PlCz5PjService', true],
            'App\\Controller\\NotaController:restaurar' => ['privates', '.service_locator.UdS6csr', 'get_ServiceLocator_UdS6csrService', true],
            'App\\Controller\\RegistrationController:busqueda' => ['privates', '.service_locator.cbR_.A0', 'get_ServiceLocator_CbR_A0Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\NotaController::busqueda' => '?',
            'App\\Controller\\NotaController::delete' => '?',
            'App\\Controller\\NotaController::edit' => '?',
            'App\\Controller\\NotaController::eliminadas' => '?',
            'App\\Controller\\NotaController::index' => '?',
            'App\\Controller\\NotaController::publicas' => '?',
            'App\\Controller\\NotaController::restaurar' => '?',
            'App\\Controller\\RegistrationController::busqueda' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\NotaController:busqueda' => '?',
            'App\\Controller\\NotaController:delete' => '?',
            'App\\Controller\\NotaController:edit' => '?',
            'App\\Controller\\NotaController:eliminadas' => '?',
            'App\\Controller\\NotaController:index' => '?',
            'App\\Controller\\NotaController:publicas' => '?',
            'App\\Controller\\NotaController:restaurar' => '?',
            'App\\Controller\\RegistrationController:busqueda' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
