<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5JWiPLO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5JWiPLO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5JWiPLO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5JWiPLO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5JWiPLO\App_KernelDevDebugContainer([
    'container.build_hash' => '5JWiPLO',
    'container.build_id' => '57159556',
    'container.build_time' => 1669233435,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5JWiPLO');
